version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=zosia
      - POSTGRES_USER=zosia
      - POSTGRES_PASSWORD=zosia
      
  web:
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    image: zosia_dev
    command: >
      bash -c "python3 manage.py collectstatic --no-input
      && python3 manage.py migrate
      && uwsgi --ini /app/uwsgi.dev.ini"
    # volumes:
    #   - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
