version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=zosia
      - POSTGRES_USER=zosia
      - POSTGRES_PASSWORD=zosia
  web:
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    image: zosia_dev
    command: sleep infinity
    volumes:
      - ./app/src:/code/src
      - ./app/js:/code/js
      - ./app/static:/code/static
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - db
    links:
      - db
