version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=zosia
      - POSTGRES_USER=zosia
      - POSTGRES_PASSWORD=zosia
  web:
    build:
      context: ./app
      dockerfile: DockerfileDev
    image: zosia_dev
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - db
    links:
      - db
