version: 2.1

jobs:
  build_and_push_to_ecr:
    environment:
      AWS_ACCOUNT_ID: "463715963173"
      AWS_DEFAULT_REGION: "eu-central-1"
    docker:
      - image: docker:git
    steps:
      - run:
          name: Install awscli
          command: |
            apk add --no-cache py-pip
            pip install awscli
      - run:
          name: Build docker images
          command: docker-compose -f docker-compose.prod.yml build
      - run:
          name: Push image to ECR
          command: AWS_ACCESS_KEY_ID=${AWS_ACCESS_ID} AWS_SECRET_ACCESS_KEY=${AWS_ACCESS_SECRET_KEY} ./tools/upload_circle.sh

workflows:
  version: 2.1
  build:
    jobs:
      - build_and_push_to_ecr:
          filters:
            branches:
              only: aws_deployment
